export let choreSet = {
  daily: [
    "Clear daily clutter",
    "Wipe down kitchen counters",
    "Sort mail and incoming paperwork",
    "Prepare healthy meals",
    "Take daily vitamins/medication",
    "Feed pets",
    "Make coffee/tea and clean maker",
    "Quick bathroom tidy-up",
    "Light vacuum or sweep",
    "Wash dishes/load dishwasher",
    "Screen-free wind-down (30 min before bed)",
    "Set digital-boundary check-in",
    "Brief mindfulness or meditation session",
    "Track daily expenses",
    "Check calendar and daily tasks",
    "Take out daily kitchen trash",
    "Fill water pitchers/filters",
    "Ventilate apartment",
    "Exercise or stretch",
    "Write one gratitude entry",
    "Sanitize phones and keys",
    "Organize personal workspace",
    "Quick clothing tidy-up",
    "Water essential houseplants",
    "Secure doors/windows at night",
    "Drink a full glass of water on waking",
    "Take a 5-minute posture reset each hour",
    "Practice 1 minute of deep belly breathing",
    "Spend 5 minutes in direct sunlight",
    "Write a short intention for the day",
    "Take a 10-minute walk after a meal",
    "Floss and brush teeth thoroughly",
    "Complete a quick skincare routine",
    "Stretch wrists and shoulders (desk break)",
    "Delete five unnecessary photos or screenshots",
    "Send one meaningful message to a friend",
    "Review events seven days ahead",
    "Update habit tracker",
    "Flush kitchen sink drain with hot soapy water",
    "Shake out entryway doormat",
    "Refresh pet water and clean bowls",
    "Move food scraps to compost bin",
    "Smooth bed linens and fluff pillows",
    "Disinfect light switches and door handles",
    "Skim news headlines (≤10 min limit)",
    "Do a CBT-style thought reframe or prompt",
    "Offer three small acts of kindness",
    "Take a one-song dance break",
    "Check chair and monitor ergonomics",
    "Refill your “next-actions” task buffer",
    "Finish a two-minute micro-learning snippet",
    "Lay out tomorrow’s outfit and gear",
    "Collect stray dishes from living areas",
    "Clean keyboard and mouse surfaces",
    "Empty lint trap if laundry was run",
    "Note one personal strength used today",
    "Take allergy meds if needed",
    "Adjust layers for comfortable temperature",
    "Practice one foreign-language phrase",
    "Do a phone-scroll posture check",
    "Clean eyeglasses",
    "Spend two minutes playing with your pet",
    "Stretch calves and ankles",
    "Diffuse or light a calming scent",
    "Glance at personal values list",
    "Write a one-line positive affirmation",
    "Set a timer for the next water break",
    "Do ten body-weight squats or wall push-ups",
    "Review credit-card notifications",
    "Wipe dining table after meals",
    "File one document (digital or paper)",
    "Declutter one small drawer or shelf",
    "Check fridge thermometer reading",
    "Replace kitchen sponge if it smells",
    "Water balcony plants or herbs",
    "Wipe bathroom faucet quickly",
    "Verify locks before leaving home",
    "Place shoes neatly in rack",
    "Rotate and fluff sofa cushions",
    "Polish bathroom mirror smudges",
    "Scan receipts into budgeting app",
    "Top up the pet-food container",
    "Induce a good laugh (video or memory)",
    "Do a quick body-scan before bed",
    "Review step count or activity ring",
    "Stretch hip flexors (standing lunge)",
    "Write a one-sentence nightly reflection",
    "Switch lights to warmer hue after sunset",
    "Check hamper level; plan laundry",
    "Rinse reusable water bottle",
    "Pre-plan tomorrow’s protein source",
    "Delete five unnecessary emails",
    "Tidy charging cables; unplug idle devices",
    "Practice mindful chewing for one bite",
    "Dust leaves of a houseplant",
    "Add loose change to savings jar",
    "Spend two minutes visualizing a big goal",
    "Sing or hum a favorite tune",
    "Take five slow breaths when stressed",
    "Read an uplifting quote before sleep",
  ],
  multiple_times_a_week: [
    "Laundry (gym clothes, essentials)",
    "Sweep floors",
    "Vacuum high-traffic areas",
    "Clean pet litter/pet spaces",
    "Grocery check/restock essentials",
    "Clean bathroom sinks/mirrors",
    "Meal planning and prep",
    "Wipe down kitchen appliances",
    "Check bills/payment reminders",
    "Restock bathroom essentials (TP, soap)",
    "Clean microwave interior",
    "Update short-term budget",
    "Laundry sorting and folding",
    "Inspect fridge contents",
    "Replace towels and kitchen linens",
    "Organize shoes and jackets",
    "Sanitize high-touch surfaces",
    "Plan a meaningful social connection",
    "Tidy pantry and cabinets",
    "Plan workouts/exercise routine",
    "Review weekly nutrition goals",
    "Clean coffee table and dining area",
    "Hobby or creative session",
    "Empty small trash bins",
    "Check medication supply",
    "Clear expired fridge items",
    "Quick car tidying",
    "Digital-detox block (2 hrs)",
    "Sunlight/Outdoor time (20 min)",
    "Clean workspace electronics",
    "Cut and prep fresh produce for snacks",
    "Refill water filter cartridges if needed",
    "Sanitize reusable grocery bags",
    "Deep stretch or yoga flow (15 min)",
    "Vacuum upholstery on sofas",
    "Wipe inside fridge shelves and bins",
    "Plan three balanced breakfasts",
    "Write or refine a weekly gratitude list",
    "Call or video chat with a family member",
    "Practice a musical instrument (15 min)",
    "Batch cook a protein source",
    "Review upcoming appointments",
    "Water balcony or patio plants thoroughly",
    "Descale coffee maker or kettle",
    "Change kitchen hand towels",
    "Donate or recycle unwanted mail",
    "De-fuzz clothing with lint roller",
    "Check tire tread and pressure visually",
    "Reconcile transactions in budgeting app",
    "Declutter bedside table",
    "Clean showerhead with vinegar soak",
    "Wipe down door frames and handles",
    "Vacuum or sweep under sofa cushions",
    "Practice language flashcards (10 min)",
    "Journal a longer reflection session (10 min)",
    "Schedule social-media limits for the week",
    "Strength workout (bodyweight or weights)",
    "Plan and shop for healthy snacks",
    "Listen to an educational podcast episode",
    "Practice box breathing for 5 minutes",
    "Oil wooden cutting boards",
    "Groom pets (brush fur or clip nails)",
    "Check upcoming birthdays or events",
    "Maintain inbox zero routine",
    "Rotate pantry items first-in-first-out",
    "Clean bathroom fan vent cover",
    "Dust electronics and screens",
    "Review progress on personal goals",
    "Update grocery list in app",
    "Spend 30 minutes on a hobby project",
    "Polish shoes and condition leather",
    "Wipe windowsills and tracks",
    "Test smoke detector chirp (quick test)",
    "Replace toothbrush heads if three months old",
    "Plan date night or solo adventure",
    "Clean and disinfect trash-can lids",
    "Practice mindful eating for one meal",
    "Donate or discard one unused item",
    "Foam-roll calves or quads",
    "Update backups to external drive/cloud",
    "Do a short HIIT cardio session",
    "Wipe down gym equipment or yoga mat",
    "Clean stove drip pans",
    "Perform a random act of kindness",
    "Refill spice jars",
    "Inspect indoor plants for pests",
    "Update vision board or goals board",
    "Complete a 20-minute reading session",
    "Write thank-you or appreciation messages",
    "Rinse car exterior or windshield",
    "Organize computer desktop files",
    "Clean blender gasket and base",
    "Mend or sew small clothing tears",
    "Rotate stocked canned goods",
    "Wash reusable masks or face coverings",
    "Replace or microwave-sanitize kitchen sponges",
    "Practice a guided meditation session",
    "Do a mobility drill routine",
    "Plan entertainment or fun budget envelope",
    "Stretch hamstrings and hip flexors (long hold)",
  ],
  weekly: [
    "Dust furniture and surfaces",
    "Deep vacuum carpets",
    "Full apartment mop",
    "Change bedding and pillowcases",
    "Clean bathroom fully (shower, toilet)",
    "Take out recycling",
    "Water all plants thoroughly",
    "Weekly grocery shopping",
    "Deep clean kitchen surfaces",
    "Clean mirrors and windows",
    "Clean trash bins",
    "Check smoke detectors",
    "Organize digital workspace",
    "Update weekly meal plan",
    "Clean computer keyboard/mouse",
    "Check pantry inventory",
    "Weekly laundry (full loads)",
    "Check car tire pressure",
    "Meal prep (freezing portions)",
    "Organize closet/wardrobe",
    "Financial check-in (expenses, savings)",
    "Nature outing or long walk",
    "Clean entryway/foyer area",
    "Deep-clean kitchen sink",
    "Wash bath mats",
    "Sort paperwork into folders",
    "Review weekly goals/tasks",
    "Inspect personal care supplies",
    "Clean patio/balcony area",
    "Vacuum under beds and large furniture",
    "Wipe down kitchen cabinet fronts",
    "Disinfect door handles and light switches",
    "Dust ceiling fan blades",
    "Clean dishwasher filter",
    "Clean lint filter housing in dryer",
    "Descale showerhead",
    "Rotate sofa cushions",
    "Sharpen kitchen knives",
    "Scrub kitchen trash can interior",
    "Refill pet food storage bins",
    "Groom pets (bath or thorough brushing)",
    "Deep clean coffee maker or kettle",
    "Fertilize balcony or house plants",
    "Polish mirrors for streak-free shine",
    "Purge expired pantry items",
    "Vacuum car interior thoroughly",
    "Wipe dashboard and console surfaces",
    "Clean inside of oven door glass",
    "Wash and sanitize makeup brushes",
    "Back up phone photos to cloud storage",
    "Update household master to-do matrix",
    "Write a weekly gratitude recap",
    "Plan one social or community event",
    "Audit personal screen-time stats",
    "Extended yoga or stretch session",
    "Check air-purifier filter indicator",
    "Test carbon-monoxide detector",
    "Clean refrigerator drawers",
    "Deep condition hair or scalp",
    "File nail care and moisturize hands",
    "Update personal or work Kanban board",
    "Polish stainless-steel appliances",
    "Disinfect remote controls and gamepads",
    "Refresh reading list and pick next book",
    "Practice a creative-skill lesson",
    "Review upcoming bills and automate payments",
    "Clean sink drain with baking soda & vinegar",
    "Vacuum mattress surface",
    "Change hand towels in bathrooms",
    "Clean shower curtain or liner",
    "Oil wooden cutting boards",
    "Vacuum sofa crevices",
    "Declutter entryway shoe rack",
    "Sort digital downloads folder",
    "Pay down credit-card balance (if any)",
    "Review progress toward quarterly goals",
    "Prep healthy grab-and-go snacks",
    "Polish leather shoes or bags",
    "Disinfect yoga mat",
    "Deep clean stovetop grates",
    "30-minute nature photography walk",
    "Refill soap dispensers",
    "Rotate emergency water supply",
    "Check tires for nails or damage",
    "Vacuum baseboards",
    "Dust window blinds",
    "Clean grout lines in bathroom floor",
    "Stretch hip flexors with foam roller",
    "Organize toolbox or repair kit",
    "Write a personal reflection journal page",
    "Plan weekly date night or self-care block",
    "Organize medicine cabinet",
    "Review and cancel unused subscriptions",
    "Test flashlight batteries",
    "Clean microwave turntable and interior walls",
    "Polish glass stovetop",
    "Shred sensitive junk mail",
    "Wash reusable grocery bags",
    "Replace fridge water filter if due",
    "Deep clean kitchen backsplash",
  ],
  biweekly_to_monthly: [
    "Wash throw blankets/covers",
    "Deep clean refrigerator interior",
    "Dust ceiling fans and vents",
    "Vacuum upholstery (sofas, chairs)",
    "Clean dishwasher and disposal",
    "Review monthly budget",
    "Inspect personal hygiene items",
    "Deep clean oven/stove",
    "Organize fridge/freezer storage",
    "Shred unnecessary paperwork",
    "Digital declutter",
    "Wash curtains/window treatments",
    "Clean vehicle interior and exterior",
    "Check air purifier/replace filter",
    "Inventory household essentials",
    "Restock cleaning supplies",
    "Inspect electronics cords/safety",
    "Review subscriptions/services",
    "Clean under furniture",
    "Check expiration dates (pantry, medicines)",
    "Organize storage areas/closets",
    "Backup important digital data",
    "Deep clean bathroom cabinets",
    "Inspect apartment for minor repairs",
    "Clean washing machine/dryer",
    "Defrost and deep clean freezer",
    "Clean dryer vent hose and exterior vent cover",
    "Deep scrub bathroom grout with brush",
    "Polish wood furniture with beeswax conditioner",
    "Vacuum dust from refrigerator coils",
    "Clean window tracks and lubricate sliders",
    "Wash inside of windows and screens",
    "Descale toilet tank with vinegar soak",
    "Clean range hood filters in hot soapy water",
    "Condition leather furniture or accessories",
    "Organize craft or hobby supplies",
    "Sort and archive digital photos into albums",
    "Update and rotate emergency water and food supplies",
    "Check and reset GFCI outlets",
    "Tighten loose door handles and knobs",
    "Trim indoor plants and remove dead leaves",
    "Paginate and file important mail or receipts",
    "Clean behind refrigerator and stove",
    "Check and patch minor wall scuffs/paint touch-ups",
    "Lubricate door hinges and squeaky joints",
    "Replace or clean vacuum filters",
    "Check water heater pressure relief valve",
    "Vacuum furnace register vents and returns",
    "Inspect shower caulking for mold or cracks",
    "Purge expired condiments and sauces",
    "Deep clean trash cans with bleach solution",
    "Reorganize linen closet and fold sheets",
    "Steam clean upholstered dining chairs",
    "Check bike or scooter maintenance (tire pressure, chain oil)",
    "Clean and seal countertops (granite, butcher block)",
    "Sanitize pantry shelves and sweep crumbs",
    "Polish silverware or special cookware",
    "Deep soak reusable water bottles and lids",
    "Clean and descale humidifiers",
    "Update password manager and enable 2FA checks",
    "Review loyalty programs and redeem points",
    "Inspect for signs of pests and seal gaps",
    "Deep clean balcony or outdoor furniture cushions",
    "Replace baking soda deodorizer boxes in fridge",
    "Organize and digitally archive tax receipts",
    "Polish and wax hardwood floors in high-traffic zones",
    "Clean and sanitize pet toys",
    "Check and clean washing machine detergent drawer",
    "Inventory first-aid kit contents",
    "Deep clean air vents and replace filters if dirty",
    "Lubricate sliding door tracks",
    "Tighten loose furniture screws and bolts",
    "Apply mildew-resistant spray to tile grout",
    "Clean coffee grinder burrs",
    "Flush sink aerators to remove mineral deposits",
    "Deep clean inside of garbage disposal with ice and citrus",
    "Organize photo backups on external drive",
    "Wash car floor mats and vacuum trunk",
    "Rotate sofa and chair legs felt pads",
    "Test and clean remote-control batteries contact points",
    "Clean exterior window sills and ledges",
    "Inspect grout in kitchen backsplash and reseal if needed",
    "Clean and sanitize lunch boxes or meal-prep containers",
    "Polish brass or metal fixtures",
    "Evaluate auto-renewing memberships for relevance",
    "Clean and lubricate scissors and kitchen shears",
    "Deep soak and whiten white socks or towels",
    "Inspect light bulbs and replace dim or burnt-out ones",
    "Check extension cords and power strips for wear",
    "Reinforce loose shelving anchors",
    "Polish glass light fixtures and shades",
    "Dust and vacuum behind headboard",
    "Update household inventory list for insurance purposes",
    "Wipe wax residue from candle holders",
    "Sanitize door mats with disinfectant spray",
    "Review and declutter fridge magnets and notes",
    "Deep clean keyboard with compressed air",
    "Refresh or replace potpourri or scent diffusers",
    "Practice a 30-minute creative writing sprint",
    "Review month’s accomplishments and celebrate wins",
  ],

  quarterly_to_semi_annually: [
    "Flip/rotate mattress",
    "Deep clean carpets/rugs",
    "Organize seasonal clothes",
    "Check fire extinguishers",
    "Deep clean windows/screens",
    "Wash pillows and comforters",
    "Medical/dental appointments scheduling",
    "Check HVAC filters",
    "Pest control checks",
    "Review long-term financial goals",
    "Check apartment lease conditions",
    "Inspect plumbing fixtures",
    "Car maintenance (oil change, fluids)",
    "Inspect/clean balcony furniture",
    "Quarterly life reflection journal",
    "Deep clean closets/storage spaces",
    "Review insurance coverage",
    "Check emergency preparedness",
    "Evaluate health insurance coverage",
    "Update emergency contact information",
    "Plan travel/vacation schedule",
    "Deep-clean stovetop hood",
    "Review and adjust investments",
    "Organize important personal documents",
    "Replace toothbrush/essential hygiene tools",
    "Deep clean dryer vent duct",
    "Reseal grout or caulk in wet areas",
    "Test smoke and CO alarms fully",
    "Drain and flush water-heater sediment",
    "Rotate or flip seat cushions for even wear",
    "Descale shower heads thoroughly",
    "Conduct a digital-security audit",
    "Purge and archive email inbox",
    "Donate clothes not worn this past season",
    "Take a solo reset day or mini retreat",
    "Update will or estate documents",
    "Obtain and review credit reports",
    "Replace refrigerator water filter",
    "Remove oven racks and deep clean interior glass",
    "Vacuum behind fridge and stove; clean coils",
    "Wash window treatments (blinds, drapes)",
    "Wash walls and baseboards throughout home",
    "Shampoo upholstered furniture",
    "Wash and wax car exterior; deep-clean interior",
    "Replace or wash shower curtain/liner",
    "Organize digital photo library and back up",
    "Replace kitchen sponges and dish brushes",
    "Inspect ceilings/roof for leaks or stains",
    "Audit and cancel unused subscriptions",
    "Clean and condition leather goods",
    "Prune social-media follows to reduce noise",
    "Review professional-development progress",
    "Clean fridge gaskets and coils",
    "Lubricate door hinges, locks, and sliders",
    "Update six-month budget projections",
    "Rotate and restock emergency supplies",
    "Inspect spare tire and car emergency kit",
    "Remove and clean HVAC vent covers",
    "Polish and re-wax hardwood floors",
    "Reseal stone or granite countertops",
    "Repot or fertilize larger houseplants",
    "Replace thermostat batteries",
    "Review privacy settings across major apps",
    "Clean lighting fixtures and replace aged bulbs",
    "Reassess charitable donations or volunteering",
    "Schedule recommended health screenings/labs",
    "Reevaluate fitness plan; set new targets",
    "Purge expired cosmetics and bathroom products",
    "Wash and store off-season bedding/linens",
    "Deep scrub litter box; replace all filler",
    "Test sump-pump functionality (if applicable)",
    "Declutter and sweep garage or storage locker",
    "Replace smoke-detector batteries proactively",
    "Service bicycles (lube chain, brake check)",
    "Clean gutters or balcony drains",
    "Replace pitcher/faucet water filters",
    "Inspect window and door seals for drafts",
    "Rotate pantry staples; donate older goods",
    "Audit household chemicals; dispose safely",
    "Update emergency cash reserve location",
    "Review asset allocation across investments",
    "Deep clean grill or barbecue equipment",
    "Plan a digital-detox weekend retreat",
    "Organize hobby gear; donate unused items",
    "Check immunizations and booster status",
    "Conduct a household emergency drill",
    "Wash pet bedding, carriers, and toys",
    "Refresh or create an updated vision board",
    "Review life-insurance coverage and beneficiaries",
    "Scrub behind toilets; remove hard-water scale",
    "Inspect and clean fireplace or chimney flue",
    "Polish silverware, copper, or brass items",
    "Replace windshield wipers; top vehicle fluids",
    "Clean laptop vents; update OS and back-ups",
    "Review retirement-plan contribution levels",
    "Install or replace low-flow shower heads",
    "Deep clean inside kitchen cabinets; reorganize",
    "Schedule dental cleaning if due",
    "Host a gratitude or reflection dinner",
    "Celebrate quarterly achievements with a day trip",
  ],
  annual_or_as_needed: [
    "File income taxes",
    "Annual medical check-up",
    "Dental cleaning/check-up",
    "Vision check-up",
    "Renew vehicle registration/license",
    "Review/renew apartment lease",
    "Perform annual credit-report review",
    "Assess and rebalance retirement accounts",
    "Create/update personal will",
    "Evaluate professional development",
    "Plan holiday/birthday gifts",
    "Update resume/professional portfolio",
    "Evaluate housing/apartment satisfaction",
    "Personal retreat or day trip",
    "Plan vacations/time off",
    "Schedule comprehensive blood panel and labs",
    "Get annual flu vaccine (or other seasonal shot)",
    "Replace smoke- and CO-alarm units if over 10 years old",
    "Professional carpet or rug cleaning",
    "Pressure-wash exterior balcony or patio surfaces",
    "Request full HVAC duct cleaning/inspection",
    "Review all insurance policies for adequate coverage",
    "Purge and organize long-term storage boxes",
    "Shred tax documents past legal-retention period",
    "Donate unused clothes and household items",
    "Update beneficiaries on financial and insurance accounts",
    "Refresh emergency contacts in phone and HR records",
    "Renew or refresh CPR/first-aid certification",
    "Change master password and audit password manager",
    "Replace pillows and mattress toppers if worn",
    "Set digital-legacy preferences for key accounts",
    "Full-body dermatology (skin-cancer) screening",
    "Audiology/hearing test",
    "Comprehensive dilated eye exam",
    "Recharge or replace household fire extinguishers",
    "Deep clean refrigerator coils and drain pan",
    "Prune trees or large balcony plants",
    "Inspect visible plumbing for slow leaks",
    "Professional water-heater flush/service",
    "Clean entire dryer-vent run from appliance to exterior",
    "Tune up major kitchen and laundry appliances",
    "Archive and declutter cloud-storage drives",
    "Complete a personal carbon-footprint audit",
    "Review and plan charitable giving strategy",
    "Make a full computer backup to offline drive",
    "Enable/refresh two-factor authentication everywhere",
    "Update long-term vision board and life goals",
    "Host an annual gratitude dinner with loved ones",
    "Schedule a therapeutic massage or bodywork session",
    "Update eyewear prescription and order replacements",
    "Replace contact-lens cases and bulk solution supply",
    "Renew key memberships (AAA, library, professional orgs)",
    "Vehicle tune-up, alignment, and fluid top-offs",
    "Tire rotation and brake-system inspection",
    "Replace vehicle cabin air filter",
    "Deep interior/exterior auto detail",
    "Renew passport (if expiring within 12 months)",
    "Tighten social-media privacy settings review",
    "Clean building gutters or balcony floor drains",
    "Inspect attic/crawlspace (or top cabinets) for pests",
    "Audit annual energy usage; plan efficiency upgrades",
    "Update home-inventory photos/videos for insurance",
    "Clean and oil any wooden decking or balcony tiles",
    "Replace batteries in rarely used devices (flashlights, radios)",
    "Exercise all water-shutoff valves to keep them functional",
    "Run oven self-clean cycle and wipe down interior",
    "Schedule professional chimney or flue sweep (if applicable)",
    "Arrange annual pest inspection and prevention treatment",
    "Revisit savings rate and long-term financial targets",
    "Select the best health-insurance plan during open enrollment",
    "Book age-appropriate screenings (colonoscopy, mammogram, etc.)",
    "Schedule at least one mental-health check-in or therapy session",
    "Plan a one-week social-media or tech detox",
    "Replace shower-liner curtain",
    "Descale and deep clean coffee machine or espresso maker",
    "Audit and cancel unused annual subscriptions",
    "Refresh supplies in emergency go-bag",
    "Verify employer 401(k) match and adjust contributions",
    "Stock a year’s worth of replacement toothbrush heads",
    "Refresh holiday-card and gift list contacts",
    "Complete full closet audit and off-season storage swap",
    "Optimize or defragment computer drives",
    "Have kitchen knives professionally sharpened",
    "Review household fire-escape plan and practice drill",
    "Service bicycles (frame, brakes, chain)",
    "Create or update a career-development or certification plan",
    "Compile an annual printed photo book",
    "Steam-clean and seal grout in tiled floors",
    "Replace under-sink or whole-home water filters",
    "Schedule dental X-rays if due",
    "Update pet vaccinations and medical records",
    "Deep wash all curtains and draperies",
    "Pull heavy appliances forward and clean behind/under",
    "Replace expired essential oils or diffuser reeds",
    "Update medical information card kept in wallet/phone",
    "Review personal budget categories; realign spending",
    "Request credit-card retention offers or better benefits",
    "Rewrite personal mission statement for the year ahead",
    "Celebrate milestones with a special experience day",
  ],
};
